### PR TITLE
Minor changes in order to be able to run the example locally

### PR DESCRIPTION
**Pull request by ezilocchi**
Hi there,

These are the changes that I had to do in order to be able to run the example locally:
1. Set minimum requirements. For instance you need ruby > 2.2.2
2. Use SQLITE instead of postgres for `development` and `test` so it's easier to start.
3. Add `typings` as `devDependency` since you are running it on the post install script.

### CODE REVIEW

**Comment by neroniaky** [comment]
Hey @ezilocchi thanks a lot for your PR!
All changes make a lot of sense, I'm just not sure about using sqlite because it doesn't support the JSON format. Do you have any insight if changing the datatype to `text` makes any difference for `devise token auth`? I don't have enough experience with sqlite to tell.

**Comment by ezilocchi** [comment]
@neroniaky as far I as I know `json` datatype is specific to the `postgresql` implementation, since it's a special data type that postgresql provides. Regardless that, rails allows you to store a `json` object as string in a column of type `text` (you can check [here](http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html)). 

Of course if you are using postgresql as database you should make use of the `json` type, it will be better, but for an example purpose I think it doesn't matter really, the main goal is to have a easy-to-run app that shows how to use the library, and removing postgresql from the stack make things simple :). As you can see I leave postgresql on the production configuration.

Anyway I've tested locally and it worked 😄  so I guess that it's fine.

**Comment by neroniaky** [comment]
Thanks a lot @ezilocchi !

**Comment by ezilocchi** [comment]
😊

**Pull request merged**
